name: Build and Publish Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      PUBLISH_TOKEN: ${{ secrets.JB_TOKEN }}
    steps:
      - name: Extract Version Tag
        run: echo "PLUGIN_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: build and publish plugin
        run: |
          echo ${{ env.PLUGIN_VERSION }}
          ./gradlew buildPlugin 
          ls ./build/distributions
#          ./gradlew --no-daemon publishPlugin

      - name: Create Github Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}


      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/distributions/AdaptiveCaretScroll-${{ env.PLUGIN_VERSION }}.zip
          asset_name: AdaptiveCaretScroll-${{ env.PLUGIN_VERSION }}.zip
          asset_content_type: application/gzip

          
    

