name: Build and Publish Plugin

on: push
#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      PUBLISH_TOKEN: ${{ secrets.JB_TOKEN }}
#      PLUGIN_VERSION: 1.0.2
      PLUGIN_VERSION: ${{ github.ref }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: build and publish plugin
        run: |
          echo ${{ env.PLUGIN_VERSION }}
          ./gradlew buildPlugin 
          ls ./build/distributions
#          ./gradlew --no-daemon publishPlugin

      - name: Create Github Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/AdaptiveCaretScroll-${{ env.PLUGIN_VERSION }}.zip
          asset_name: AdaptiveCaretScroll-${{ env.PLUGIN_VERSION }}.zip
          asset_content_type: application/gzip

          
    

